### ISSUE TITLE
Small issue with conditionals

### ISSUE THREAD

**Issue by zachfedor** [ts-cset/green-portal#28]
https://github.com/ts-cset/green-portal/blob/297962119d5badb2001c01b7557b4b474a061afa/portal/sessions.py#L33-L35

There are only two possible branches for these conditionals, right? Either the role is the string of "teacher" or not. Since there's only two branches, we should have an `if/else` clause not an `if/elif` clause which implies more than two branches.

**Comment by Tfink13** [comment]
Fixed the issue in the sessions.py file and also in the courses.py file
